apiVersion: v1
kind: Service
metadata:
  # Service name
  name: chai-app-service
  namespace: chai-app
spec:
  selector:
    app: chai-app
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
  type: ClusterIP
